server.port=5000
spring.data.mongodb.uri=mongodb+srv://hjcchathurya:20181023jc@oceanviewresortsystem.1qinics.mongodb.net/test?appName=oceanviewresortsystem
spring.data.mongodb.database=test

# JWT Secret
jwt.secret=supersecret123

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Email Configuration (Replace with actual credentials for production)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hjcchathurya@gmail.com
spring.mail.password=bvgimdhremgvonyg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
